package io.jboot.codegen.model.test;

import io.jboot.db.annotation.Table;
import io.jboot.codegen.model.test.base.BaseArticle;

/**
 * Generated by Jboot.
 */
@Table(tableName = "Article", primaryKey = "id")
public class Article extends BaseArticle<Article> {
	
}
