package io.jboot.codegen.model.test;

import io.jboot.db.annotation.Table;
import io.jboot.codegen.model.test.base.BaseUser;

/**
 * Generated by Jboot.
 */
@Table(tableName = "User", primaryKey = "id")
public class User extends BaseUser<User> {
	
}
